
Vagrant.configure("2") do |config|
  
    config.vm.box = "bento/ubuntu-16.04"
  
    config.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
    end
  
    config.vm.define "master" do |master|
        master.vm.network "private_network", ip: "192.168.33.10"
        
        master.vm.provision "shell", inline: <<-SHELL
            echo "Installing consul"
            apt-get update
            apt-get install -y unzip dnsmasq
            wget https://releases.hashicorp.com/consul/1.4.0/consul_1.4.0_linux_amd64.zip -O consul.zip --quiet
            unzip consul.zip >/dev/null
            chmod +x consul
            #run consul
            echo "Running consul"
            ./consul agent -dev -enable-script-checks -bind "192.168.33.10" -node=master -client "0.0.0.0" > logs.consul &
                
            echo "Setting up dns"
            echo "server=/consul/192.168.33.10#8600" > /etc/dnsmasq.d/10-consul
            systemctl restart dnsmasq
        SHELL
    end
  end
  