apiVersion: apps/v1
kind: Deployment
metadata:
  name: consul
spec:
  selector:
    matchLabels:
      run: consul
  replicas: 1
  template:
    metadata: 
      labels:
        run: consul
    spec:
      containers:
      - name: consul
        image: consul
        ports:
        - containerPort: 8500

---
apiVersion: v1
kind: Service
metadata:
  name: consul
  labels:
    run: consul
spec:
  ports:
  - port: 8500
    targetPort: 8500
    protocol: TCP
  selector:
    run: consul
  type: LoadBalancer