
Vagrant.configure("2") do |config|
  
  config.vm.box = "bento/ubuntu-16.04"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end

  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get upgrade
    sudo curl -fsSL get.docker.com -o get-docker.sh
    sudo sh get-docker.sh
    sudo rm get-docker.sh
    sudo usermod -aG docker vagrant
  SHELL

  config.vm.define "master" do |master|
    master.vm.network "private_network", ip: "192.168.33.10"

    master.vm.synced_folder "../../DockerSwarm", "/playground"
  end

  config.vm.define "node1" do |node1|
    node1.vm.network "private_network", ip: "192.168.33.11"
  end

  config.vm.define "node2" do |node2|
    node2.vm.network "private_network", ip: "192.168.33.12"
  end
end
