apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: kubejob
spec:
  schedule: "0/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: kubejob
            image: krystiankolad/kube.job
          restartPolicy: OnFailure